# Stage 1: Build the web app
FROM ghcr.io/cirruslabs/flutter:3.32.0-0.5.pre AS build

WORKDIR /app

COPY aegleone/ .

RUN flutter pub get
RUN flutter build web --debug
# Uncomment the following line if you want to build the web app in release mode (production)
# RUN flutter build web --release

# Stage 2: Serve the web app with Nginx
FROM nginx:1.28-alpine

COPY --from=build /app/build/web /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]