services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/aegleone:/app
      - backend_static:/app/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
    networks:
      - app-network
  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile.web
    volumes:
      - ./frontend/aegleone:/app
    ports:
      - "8080:80" # 80 from the container to 8080 on the host
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  backend_static:


networks:
  app-network:
    driver: bridge
